name: Update Submodule

on:
  schedule:
    - cron: "30 17 * * *" # Ejecutar diariamente a las 17:30 UTC (14:30 Chile)
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true # Asegura que los submódulos también sean descargados

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull changes for submodule
        run: |
          cd nvim # Cambia al directorio del submódulo
          git pull origin master # Hacer pull de los cambios en el submódulo
          cd .. # Regresar al directorio principal
          git add nvim
          git commit -m "Update submodule" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Usar el token de GitHub Actions
